matter-labs/block-explorer

packages/api/Dockerfile
packages/worker/Dockerfile

Fix for Block Explorer Worker migrations.
Since Worker was moved to `packages/worker` folder, to make TypeOrm migrations work, the directory from where Worker is started must be changed.

fix: change docker file workdir to fix worker migrations

---

packages/app/src/components/transactions/infoTable/GeneralInfo.vue
packages/app/src/components/transactions/infoTable/TransferTableCell.vue
packages/app/src/composables/useTransaction.ts
packages/app/tests/components/transactions/GeneralInfo.spec.ts

If transaction doesn't have at least one transfer with amount - we don't show tokens transferred component on transaction page.
We can't show such transfers properly atm.

fix: do not show tokens transferred component for transactions with no transfers having amount

---

docker-compose.yaml
packages/app/src/composables/useEnvironmentConfig.ts
packages/app/src/configs/dev.config.json
packages/app/src/configs/local.config.json

Separate App configurations for local and dev setups.
For development setup we're gonna show all networks, but for local (which will be used when running from CLI) only Local network will be shown.
**Dev (default if you just run the application):**
**Local (will be used by CLI):**

chore: separate app config for local and dev

---

.github/workflows/release.yml
docker-compose-cli.yaml
docker-compose.yaml
packages/app/Dockerfile

Docker compose file for CLI. Multi stage Docker file for App package.
We need a slightly different docker compose configuration for CLI, so it was added.
Docker file for App was changed to multi stage to make build consistent across all packages and introduce different stages for dev and prod envs.

chore: docker compose for cli

---

packages/app/src/composables/useAddress.ts
packages/app/src/composables/useContractABI.ts
packages/app/src/configs/dev.config.json
packages/app/src/configs/index.ts
packages/app/src/configs/local.config.json
packages/app/tests/composables/useAddress.spec.ts
packages/app/tests/composables/useContractABI.spec.ts
packages/app/tests/mocks.ts

- Do not request contract verification info when running against local node
- Since contract verification is not yet implemented in the Block Explorer API the request simply fails and any contract page becomes unavailable

fix: do not request verification info when running local node

---

packages/worker/package.json
packages/worker/src/blockchain/blockchain.service.ts
packages/worker/src/entities/token.entity.ts
packages/worker/src/transformers/string.transformer.spec.ts
packages/worker/src/transformers/string.transformer.ts

Remove 0 bytes from strings before saving into DB
Postgres can't save strings containing 0 bytes.
- [ +] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [+ ] Tests for the changes have been added / updated.

fix: remove 0 bytes from strings before saving into DB

---

packages/api/src/api/api.controller.spec.ts
packages/api/src/api/api.controller.ts

Improved docs for txlistinternal api endpoint
It's more user friendly to have separate swagger definitions for txlistinternal endpoint without params, with address and with txHash param.

fix: docs for txlistinternal api endpoint

---

packages/api/src/api/account/account.controller.spec.ts
packages/api/src/api/mappers/internalTransactionMapper.spec.ts
packages/api/src/api/mappers/internalTransactionMapper.ts
packages/api/src/api/mappers/transactionMapper.spec.ts
packages/api/src/api/mappers/transactionMapper.ts
packages/api/src/api/mappers/transferMapper.spec.ts
packages/api/src/api/mappers/transferMapper.ts
packages/api/src/transaction/dtos/transaction.dto.ts
packages/api/src/transaction/entities/transaction.entity.ts
packages/api/src/transfer/transfer.service.spec.ts
packages/api/src/transfer/transfer.service.ts
packages/api/test/account-api.e2e-spec.ts
packages/api/test/address.e2e-spec.ts
packages/api/test/log-api.e2e-spec.ts
packages/api/test/stats.e2e-spec.ts
packages/api/test/token.e2e-spec.ts
packages/api/test/transaction-api.e2e-spec.ts
packages/api/test/transaction.e2e-spec.ts

Add transaction `type` to all endpoints where transaction data is returned. For _get internal transactions_ endpoint, the field is named `transactionType` since `type` is already used for other purpose.
This was requested by developers who are integrating their products with zkSync so they don't need to fetch transaction types separately from the RPC. As it makes sense to return this data anyway, it was added to all endpoints that return transaction data.

feat: add transaction type to transaction endpoints

---

packages/api/src/token/token.controller.spec.ts
packages/api/src/token/token.controller.ts
packages/api/src/token/token.service.spec.ts
packages/api/src/token/token.service.ts

- Adds min liquidity filters for /tokens API
- front-end will be able to fetch all tokens with liquidity

feat: add min liquidity filter for tokens list API

---

packages/app/src/composables/useSearch.ts
packages/app/src/router/routes.ts
packages/app/tests/composables/useSearch.spec.ts
packages/app/tests/views/AddressView.spec.ts
packages/app/tests/views/BatchView.spec.ts
packages/app/tests/views/BatchesView.spec.ts
packages/app/tests/views/BlockView.spec.ts
packages/app/tests/views/BlocksView.spec.ts
packages/app/tests/views/ContractVerificationView.spec.ts
packages/app/tests/views/DebuggerView.spec.ts
packages/app/tests/views/HomeView.spec.ts
packages/app/tests/views/TransactionView.spec.ts
packages/app/tests/views/TransactionsView.spec.ts

App search route which redirects the request to tx, batch or address route depending on the param. Examples:
```
/search?q=123 -> /batch/123
/search?q=0x7e341fa7fa5368ece4814825fd181697404b5d243172db071bf5562c02976ad5 -> /tx/0x7e341fa7fa5368ece4814825fd181697404b5d243172db071bf5562c02976ad5
/search?q=0x043927b4e501835556057472A5636e99fC247e9A -> /address/0x043927b4e501835556057472A5636e99fC247e9A
```
Unified search URL is requested by developers who work on integrations with zkSync.

feat: add search route

---

packages/app/src/components/header/TheHeader.vue
packages/app/src/locales/en.json
packages/app/src/locales/uk.json
packages/app/tests/components/TheHeader.spec.ts

Add API Documentation to the Tools menu item:
We want developers to easier find API Documentation on their own.

feat: add API docs to the menu

---

.github/workflows/app-deploy-feature-branch.yml
.gitignore
packages/app/tests/e2e/features/artifacts/artifactsSet1.feature
packages/app/tests/e2e/features/redirection/redirectionSet1.feature
packages/app/tests/e2e/features/redirection/redirectionSet3.feature

check and fix e2e tests for be if any
-
- [ +] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ -] Tests for the changes have been added / updated.
- [ -] Documentation comments have been added / updated.

test: verify e2e tests for be

---

packages/worker/src/token/tokenOffChainData/providers/portalsFiTokenOffChainDataProvider.spec.ts
packages/worker/src/token/tokenOffChainData/providers/portalsFiTokenOffChainDataProvider.ts

- remove tokens minLiquidity filter when value is 0 as provider doesn't return 0 liquidity tokens when filter is set to 0

fix: remove tokens minLiquidity filter when value is 0

---

packages/worker/src/token/token.service.spec.ts
packages/worker/src/token/token.service.ts

- validate bridge init log to be produced by bridge contract
- if token is bridged outside of bridge it can't rely on provided token l1 address

fix: add validation to check bridge init log producer

---

packages/app/src/configs/production.config.json
packages/app/tests/e2e/features/artifacts/artifactsSet3.feature

Hide Sepolia network on prod.
We need to hold off on announcing Sepolia support in Block Explorer until all other teams are ready to do this.

fix: hide sepolia network on prod

---

packages/app/src/configs/staging.config.json

fix: add sepolia staging hostname

---

README.md

- remove $ from copy-pasteable commands
- add sepolia links

chore: readme fixes

---

packages/app/src/utils/helpers.ts

- show logs without parsed event if it fails.
- currently it shows no logs at all if even one of many logs is failed to parse.
This is a quick fix for now. The issue can be reproduced with proxy contracts if there are some events emitted which are defined in the implementation contract. To properly fix it we should use both proxy and implementation ABI.

fix: ignore parse log errors

---

packages/worker/src/balance/balance.service.spec.ts
packages/worker/src/balance/balance.service.ts
packages/worker/src/block/block.processor.spec.ts
packages/worker/src/block/block.processor.ts
packages/worker/src/repositories/base.repository.spec.ts
packages/worker/src/repositories/base.repository.ts
packages/worker/src/token/token.service.spec.ts
packages/worker/src/token/token.service.ts

- Save tokens which affected balances after processing every block.
- If token initially deployed didn't have all the required attributes we need to try to save it again later.
- [+] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [+] Tests for the changes have been added / updated.

feat: re-check tokens to save based on transfers after each block

---

packages/app/src/components/header/TheHeader.vue
packages/app/src/components/token/TokenListTable.vue
packages/app/src/components/transactions/infoTable/GeneralInfo.vue
packages/app/src/composables/useTokenLibrary.ts
packages/app/src/configs/dev.config.json
packages/app/src/configs/index.ts
packages/app/src/configs/production.config.json
packages/app/src/configs/staging.config.json
packages/app/src/locales/en.json
packages/app/src/locales/uk.json
packages/app/src/router/routes.ts
packages/app/src/views/TokensView.vue
packages/app/tests/components/TheHeader.spec.ts
packages/app/tests/components/transactions/GeneralInfo.spec.ts
packages/app/tests/composables/useTokenLibrary.spec.ts

Use liquidity tokens filter only on mainnet.
To show tokens without liquidity on testnets, local envs and hyperchains.

fix: use liquidity tokens filter only on mainnet

---

packages/app/src/components/debugger/SourceViewer.vue
packages/app/src/composables/useTrace.ts
packages/app/tests/components/debugger/SourceViewer.spec.ts
packages/app/tests/views/DebuggerView.spec.ts

fix: debugger tool tests

---

packages/app/src/components/debugger/SourceViewer.vue
packages/app/src/composables/useTrace.ts
packages/app/src/views/DebuggerView.vue
packages/app/tests/components/debugger/SourceViewer.spec.ts
packages/app/tests/views/DebuggerView.spec.ts

Add background color to instructions in Debugger Tool based on instruction call count
To make it easier for compiler team to optimize pre-compiles
https://github.com/matter-labs/block-explorer/assets/1890113/08ba8a1e-6567-4c6e-a213-2f2ff894edac

feat(debugger): add background color to instructions based on call count

---

packages/app/src/App.vue
packages/app/src/components/NetworkDeprecated.vue

Deprecate warning for Goerli network:
To warn users that we are ending support of Goerli testnet.

feat: deprecate warning for goerli

---

packages/app/src/components/transactions/Status.vue
packages/app/src/locales/en.json
packages/app/src/locales/uk.json
packages/app/tests/components/transactions/GeneralInfo.spec.ts
packages/app/tests/components/transactions/Status.spec.ts

Improve transaction indexing status:
For better UX we want to show that _Indexing_ transaction status means that transaction has been already included.

fix: improve indexing status badge

---

packages/worker/src/token/token.service.spec.ts
packages/worker/src/token/token.service.ts

Do not try to save tokens whose symbols contain only special characters.
Because it violates the token DB constraint.

fix: don't save tokens whose symbols contain only special characters

---

packages/app/src/composables/useSearch.ts

Remove prefetch reuest when search by tx hash.
To be able to see search for tx that are in blockchain but hasn't been indexed yet.

fix: don't do prefetch request for tx search

---

package-lock.json
packages/app/src/App.vue
packages/app/src/components/IssuesBanner.vue
packages/app/src/components/header/TheHeader.vue
packages/worker/package.json
packages/worker/src/health/health.controller.spec.ts
packages/worker/src/health/health.controller.ts
packages/worker/src/main.ts

fix: add mainnet warning (tmp)

---

packages/app/src/components/FeeData.vue
packages/app/src/components/TheFooter.vue
packages/app/src/components/header/TheHeader.vue
packages/app/src/views/ContractVerificationView.vue
packages/app/tests/components/FeeData.spec.ts
packages/app/tests/components/TheFooter.spec.ts
packages/app/tests/components/TheHeader.spec.ts
packages/app/tests/e2e/features/redirection/redirectionSet1.feature
packages/app/tests/views/ContractVerificationView.spec.ts

Fix links to documentation.
The documentation has been updated so we should use new links.

fix: docs links

---

packages/integration-tests/tests/api/tokens.test.ts

Added test for TC id1803 /tokens/{address}/transfers endpoint
Expand test coverage - id1803 wasn't covered by autotest

test: covering tokens API endpoints tc1803

---

packages/app/tests/e2e/features/artifacts/artifactsSet1.feature
packages/app/tests/e2e/features/redirection/redirectionSet1.feature

In the scope of this PR several changes to automation tests were performed. Based on the [PR](https://github.com/matter-labs/block-explorer/pull/159). Where Portal links were removed and replaced with one solid approach - to display link to Bridge as unified platform that we currently use.
To have automation tests coverage up-to-date with recent changes and not to block ci/cd run with incorrect behaviour for old link.

fix: update tests for removing duplicate portal links 

---

packages/integration-tests/package.json
packages/integration-tests/tests/api/transactions.test.ts

Added coverage for all 0 items in responses for Transaction endpoints

test: refactor and actualise Transactions tests

---

packages/app/src/components/NetworkDeprecated.vue

New goerli deprecation message with a specific deprecation date:
To notify users when the deprecation is gonna happen.

fix: update goerli deprecation message

---

packages/testing-docs/docs/BE Tests/ Common /Header /id231 - Header - Common - External links SN icons.md
packages/testing-docs/docs/BE Tests/ Common /Header /id705 - Header - Common - Artifacts Network Drop Down.md
packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Production/id565 - Networks navigation Prod - Common - Navigation to Sepolia.md
packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Production/id566 - Networks navigation Prod - Common - Navigation to Mainnet.md
packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Staging/id561 - Networks navigation Staging - Common - Navigation to Goerli Stage2.md
packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Staging/id562 - Networks navigation Staging - Common - Navigation to zkSync Era Testnet.md
packages/testing-docs/docs/BE Tests/ Common /Networks navigation - Staging/id563 - Networks navigation Staging - Common - Navigation to Mainnet.md

Removing extra symbols that prevents page from loading.
After the test cases were imported from Allure project - some of the pages didn't load because of the different symbols.

test: remove extra symbols to avoid 404 pages redirection

---

packages/testing-docs/docs/intro.md

Added readme instructions to "Intro.md" page

feat: adding readme block with instructions to main page

---

packages/data-fetcher/src/blockchain/blockchain.service.spec.ts
packages/data-fetcher/src/blockchain/blockchain.service.ts
packages/data-fetcher/src/token/token.service.spec.ts
packages/data-fetcher/src/transfer/transfer.service.spec.ts
packages/worker/src/blockchain/blockchain.service.spec.ts
packages/worker/src/blockchain/blockchain.service.ts
packages/worker/src/token/token.service.spec.ts

Fix explorer so that a defined bridge address is not required.
In-memory node doesn't have L1 network and bridge addresses defined. This fix make explorer work with the in-memory node.

fix: explorer doesn't require defined bridge address

---

.github/workflows/app-deploy-feature-branch.yml
.github/workflows/app-deploy-preview.yml
.github/workflows/app-deploy-prod.yml
.github/workflows/release.yml

Migrate firebase jobs on self-hosted runners. 
For make contribution in frontend app from forks

ci: migrate to firebase runners

---

packages/app/src/locales/en.json
packages/app/src/locales/uk.json

Removes initial "/" from "Contract Path" placeholder.
Contract verification fails if path "/contracts/Greeter.sol" is provided instead of "contracts/Greeter.sol"

fix: contract path placeholder

---

scripts/setup-hyperchain-config.ts

Fixing default base token address value in hyperchain setup script.
Base token address on L2 is always "800A". This script might not work for hyperchains with custom L1 base token.

fix: default hyperchain base address

---

.github/workflows/app-e2e.yml
packages/app/src/components/contract/interaction/FunctionForm.vue
packages/app/src/composables/useContractInteraction.ts
packages/app/tests/composables/useContractInteraction.spec.ts

Fix next contract interaction issues:
1. https://github.com/matter-labs/block-explorer/issues/255
2. https://github.com/matter-labs/block-explorer/pull/286
To fix contract interaction issues.

fix: value argument is not being properly passed to the contract call

---

packages/worker/src/typeorm.config.ts

Get DB URL from DATABASE_URL env var in the Worker service.
To make it consistent with the API service and simplify infrastructure automation.

fix: get db url from DATABASE_URL env var in worker

---

packages/data-fetcher/src/rpcProvider/jsonRpcProviderExtended.ts
packages/worker/src/rpcProvider/jsonRpcProviderExtended.ts

Fix JSON RPC Provider timeout configuration.
This was overlooked when the explorer was migrated from an old SDK with ethers v5 to a new SDK with ethers v6.

fix: json rpc provider timeout config

---

packages/data-fetcher/src/blockchain/retryableContract.spec.ts
packages/data-fetcher/src/blockchain/retryableContract.ts
packages/worker/src/blockchain/retryableContract.spec.ts
packages/worker/src/blockchain/retryableContract.ts

Fix for the retryable contract retry functionality.
Ethers v6 returns errors differently than Ethers v5, so the function that parses an error and determines whether the request should be retried needs to be fixed.

fix: retryable contract retry functionality

---

packages/data-fetcher/src/blockchain/retryableContract.spec.ts
packages/data-fetcher/src/blockchain/retryableContract.ts
packages/worker/src/blockchain/retryableContract.spec.ts
packages/worker/src/blockchain/retryableContract.ts

Fix decode result error handling.
Currently this error case is not properly handled and the retryable contract retries requests even though this error is not retryable.

fix: decode result data error handling

---

packages/data-fetcher/src/blockchain/blockchain.service.spec.ts
packages/data-fetcher/src/blockchain/blockchain.service.ts
packages/worker/src/blockchain/blockchain.service.spec.ts
packages/worker/src/blockchain/blockchain.service.ts

Use retryable contract to get token balances.
To use reties more efficient.

fix: use retryable contract to get token balance

---

packages/worker/src/entities/transactionReceipt.entity.ts
packages/worker/src/migrations/1730806000905-TxReceiptRootColumnNullable.ts

Make tx receipt root field nullable.
RPC doesn't return this field anymore. Here is the corresponding [PR](https://github.com/matter-labs/zksync-era/pull/3187).

fix: make tx receipt root field nullable

---

.github/workflows/app-deploy-feature-branch.yml

Publish preview url only for the base repo PRs.
Even though `pull-requests: write` permissions are specified for the `Build and Test App` GitHub workflow, forked PRs are executed under `pull-requests: read` permissions. This causes the `Publish preview URL` action to fail, as it attempts to add a comment to the PR. Using the `pull_request_target` event instead of `pull_request` is not an option, as the workflow builds and runs code from the pull request context. To resolve this, the `Publish preview URL` action was modified to run only for base repository PRs. This should not be a problem for the forked PRs, as the URL is still output to the GitHub Action logs.

chore: publish preview url only for the base repo prs

---

.github/workflows/app-e2e.yml
packages/api/src/address/address.controller.ts
packages/api/src/token/token.controller.ts
packages/api/src/transaction/transaction.controller.ts

Add missing swagger type annotations for BFF endpoints.
Auto code generators that work based on the Swagger docs rely on the specified Swagger type, and if it's missing, they assume the parameter is of the object type.

fix: add missing swagger type annotations for BFF endpoints

---

packages/app/src/components/batches/InfoTable.vue

Move all Batch commit, prove and execute tx hashes into the same column
Closes #66 
Large screen
Small screen

fix: display batch details in correct columns

---

packages/app/src/components/common/table/fields/AbiData.vue
packages/app/src/locales/en.json
packages/app/src/locales/uk.json
packages/app/src/views/HomeView.vue
packages/app/tests/views/AddressView.spec.ts
packages/app/tests/views/BatchView.spec.ts
packages/app/tests/views/BatchesView.spec.ts
packages/app/tests/views/BlockView.spec.ts
packages/app/tests/views/BlocksView.spec.ts
packages/app/tests/views/ContractVerificationView.spec.ts
packages/app/tests/views/DebuggerView.spec.ts
packages/app/tests/views/HomeView.spec.ts
packages/app/tests/views/TransactionView.spec.ts
packages/app/tests/views/TransactionsView.spec.ts

* Add `View All ...` buttons on the landing page
* Fix the mobile styling of the ABI json fields for verified contracts
* Closes #97 
* With the recent change, ABI json fields are not wrapping correctly on small screens
https://github.com/user-attachments/assets/90677258-5f8b-49be-8beb-ee10cc947943

feat: add view all buttons on landing page and fix mobile styling

---

packages/app/src/components/common/Tabs.vue
packages/app/src/components/contract/ContractInfoTab.vue

Add nested routing for tabs within tabs
So we can provide links directly to sub-tabs. For example, I need a link directly to the `Read` tab of a verified contract, that would be: `https://explorer.zksync.io/address/0x000000000000000000000000000000000000800A#contract#read`
https://github.com/user-attachments/assets/6a3b4e6e-2e9e-47db-96f2-5a7e2e1ec161

feat: add nested routing

---

packages/app/src/components/event/ContractEvents.vue
packages/app/src/components/transactions/infoTable/Logs.vue
packages/app/src/components/transfers/Table.vue

Fix the display of page size dropdown with pagination component
They were overlapping wherever previously the styling of the pagination component is occurring outside of `Pagination.vue`
BEFORE:
AFTER:

fix: pagination display with page sizes

---

packages/app/src/components/SolidityEditor.vue
packages/app/tailwind.config.js

This PR preserves the lines and line numbers in contract view, so that the code lines don't break into the next line on smaller screens.
When the screen is smaller, the lines are horizontally scrollable.
PR ensures that the line number always corresponds to the correct line. Previously, on smaller screens, lines would break to the next line, causing a mismatch between lines and line numbers.
This is a fix for this issue:
https://github.com/matter-labs/block-explorer/issues/327

fix: preserve line numbers in contracts

---

packages/app/src/components/TheFooter.vue
packages/app/src/components/header/TheHeader.vue
packages/app/src/components/transactions/Table.vue
packages/app/src/composables/useOpenChain.ts
packages/app/tests/components/TheFooter.spec.ts
packages/app/tests/components/TheHeader.spec.ts
packages/app/tests/e2e/features/redirection/redirectionSet1.feature

Update display of transaction method selectors to human readable names
Closes #338

feat: update display of transaction method selectors to human readable names

---

packages/app/src/components/contract/InfoTable.vue
packages/worker/src/app.module.ts
packages/worker/src/app.service.spec.ts
packages/worker/src/app.service.ts
packages/worker/src/contract/systemContract.service.spec.ts
packages/worker/src/contract/systemContract.service.ts

This PR addresses an issue where system contracts were not displayed as contracts in the UI until they were updated. The implemented solution ensures that system contracts are loaded and saved in the database immediately after work begins. This guarantees their proper display in the UI, providing a consistent and accurate reflection of the system's state.
System contracts are not displayed as contracts in the UI until they have been updated.
This PR fixes: https://github.com/matter-labs/block-explorer/issues/358
- [+] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [+] Tests for the changes have been added / updated.

feat: add system contracts on the first run

---

packages/app/src/composables/useTransactionData.ts
packages/app/src/utils/helpers.ts
packages/app/tests/composables/useTransactionData.spec.ts
packages/app/tests/utils/helpers.spec.ts

This PR implements support for encoding non-primitive input types. With this update, all input data, including tuples, arrays, and combinations of various types, will be correctly encoded.
In the current version of the block explorer, users encounter an error when input data includes complex objects or arrays. 
For show we will use: https://explorer.zksync.io/tx/0xe39dbc98b41bb22620b78e3a3848ab34982310f9564f27d1e809cfdd461fa54e
Example without fix: 
Example with fix: 
fixes https://github.com/matter-labs/block-explorer/issues/321
- [+ ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [+ ] Tests for the changes have been added / updated.

fix: calldata encoding fails for tuple params

---

packages/api/src/balance/balance.service.spec.ts
packages/api/src/balance/balance.service.ts
packages/api/src/balance/balanceForHolder.dto.ts
packages/api/src/token/token.controller.spec.ts
packages/api/src/token/token.controller.ts
packages/api/src/token/token.module.ts
packages/app/src/components/Contract.vue
packages/app/src/components/token/TokenHoldersList.vue
packages/app/src/components/token/TokenHoldersListEmptyState.vue
packages/app/src/composables/common/Api.d.ts
packages/app/src/composables/useTokenHolders.ts
packages/app/src/locales/en.json
packages/app/src/locales/uk.json
packages/app/tests/components/token/TokenHoldersList.spec.ts
packages/app/tests/composables/useTokenHolders.spec.ts
packages/app/tests/e2e/testId.json
packages/app/tests/mocks.ts

This pull request introduces a new feature that generates a detailed token holder page, where users can view all token holders along with their respective balances. In addition to the balance, the page will display the percentage of the total token supply held by each address and provide the equivalent USD value of their holdings
To have similar detailed analytics provided on the Etherscan.
- [+] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [+] Tests for the changes have been added / updated.

feat: add holders page

---

.github/workflows/app-e2e.yml
README.md
packages/worker/README.md

Add docs for custom base token configuration for the worker service.
Base token configuration has been recently added to the worker service and it should be reflected in the docs.

docs: add custom base token config docs for worker

---

packages/app/src/components/contract/CompilationInfo.vue
packages/app/src/components/contract/ContractBytecode.vue
packages/app/src/components/contract/VerificationButton.vue
packages/app/src/composables/useAddress.ts
packages/app/src/locales/en.json

Adds visuals for automatic verification and partial matching introduced in https://github.com/matter-labs/zksync-era/pull/3527
Demo:
<details>
<summary>Unverified contract (no changes from previous behavior)</summary>
</details>
<details>
<summary>Fully verified contract (no changes from previous behavior)</summary>
</details>
<details>
<summary>Automatically verified contract</summary>
</details>
<details>
<summary>Partially verified contract (metadata hash mismatch)</summary>
</details>
<details>
<summary>Partially verified contract + automatic verification (e.g. there is a verified contract with the same bytecode but different metadata hash)</summary>
</details>
Unfortunately, since this feature depends on contract verifier version that isn't deployed anywhere yet, it's not easy to …

feat: display partial & automatic verification info

---

packages/data-fetcher/src/token/token.service.ts

On evm equiv chains, `to` can be null so we must check for it.
Without this fix, a chain cannot be indexed.

fix: fix indexing of evm equiv chains

---

packages/app/src/components/TokenIconLabel.vue
packages/app/src/components/contract/VerificationButton.vue
packages/app/src/components/token/TokenListTable.vue
packages/app/src/locales/en.json
packages/app/src/locales/uk.json
packages/app/tests/components/token/TokenListTable.spec.ts
packages/app/tests/e2e/features/artifacts/artifactsSet3.feature
packages/app/tests/e2e/features/copying.feature
packages/app/tests/e2e/features/redirection/redirectionSet2.feature
packages/app/tests/e2e/src/pages/tokens.page.ts

Add labels for bridged and native tokens.
The same token can exist both on the default bridge and on a specific bridge. To help users differentiate between them, we have added labels.
fixes https://github.com/matter-labs/block-explorer/issues/287
- [+] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [+] Tests for the changes have been added / updated.

feat: add lables for bridged and native tokens

---

packages/app/src/views/BlocksView.vue

The pagination component had both the dropdown and pagination stacked one under another.
Removing the parent wrapper fixed the alignment.
This PR fixes https://github.com/matter-labs/block-explorer/issues/386

feat: fix paging component alignment on blocks view page

---

packages/api/src/api/contract/contract.controller.spec.ts
packages/api/src/api/contract/contract.controller.ts

Add POST endpoint to check contract verification status.
To be compatible with Etherscan.

fix: add post endpoint to check verification status

---

packages/api/src/api/contract/contract.controller.spec.ts
packages/api/src/api/contract/contract.controller.ts

In the verification request, add 0x to the ctor arguments if it's missing.
To make verification endpoint compatible with Etherscan.

fix: ctor args param compatibility with etherscan

---

packages/app/src/components/contract/CodeBlock.vue
packages/app/src/components/contract/CompilationInfo.vue
packages/app/src/components/contract/ContractBytecode.vue
packages/app/src/composables/useAddress.ts
packages/app/src/locales/en.json
packages/app/tests/components/contract/CodeBlock.spec.ts
packages/app/tests/components/contract/CompilationInfo.spec.ts
packages/app/tests/components/contract/ContractBytecode.spec.ts

Improvements for the compilation info view:
1. Optimization field shows number of optimizer runs and optimizer mode if available (like Etherscan does):
2. For EVM contracts EVM Version is shown instead of Zksolc version field:
3. Compilation settings are shown below the source code (like in Etherscan). The field is copyable and expandable (like other source code fields):
To improve the UX and provide more information for the verified contracts.

fix: improve compilation info view

---

packages/app/src/composables/useAddress.ts
packages/app/src/composables/useContractVerification.ts
packages/app/src/utils/solcFullVersions.ts
packages/app/tests/composables/useAddress.spec.ts
packages/app/tests/composables/useContractVerification.spec.ts
packages/app/tests/utils/solcFullVersions.spec.ts

Show full version for solc compiler. On:
* contract verification page:
* contract verification info page:
To provide the same UX as Etherscan.

fix: show full solc compiler version

---

packages/data-fetcher/src/utils/isInternalTransaction.spec.ts
packages/data-fetcher/src/utils/isInternalTransaction.ts
packages/worker/src/token/token.service.ts

Fix transaction utils to properly handle evm transactions.
The use case when txReceipt.to is null is not fully covered.

fix: tx utils for evm eq

---

packages/data-fetcher/src/transfer/extractHandlers/finalizeDeposit/assetRouter.handler.ts

When parsing assetData from DepositFinalizedAssetRouter event one of the encoded address params could be failed to parse as it's value can exceed width (20 bytes). The fix just changes type to uint256 as the param value is never used anyway.

fix: change unused arg type from address to uint256 to avoid numeric overflow issue

---

packages/api/src/log/log.service.spec.ts
packages/api/src/log/log.service.ts
packages/app/src/composables/useContractEvents.ts
packages/app/src/composables/useSearch.ts

This PR fix several small issues found during a round of QA.
This fixes several bugs:
- The query for logs related to an addres was not scoping per address, causing the user to see all the events related to their account on every contract, instead of only the ones related to that contract.
- Sending cookies to API in a few places where we were not sending them.
- [ x ] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [ x ] Tests for the changes have been added / updated.
- [ x ] Documentation comments have been added / updated.

fix: fix log address query and missing sending cookies to API

---

packages/app/src/composables/useTransactionData.ts

- use index if name is empty in useTransactionData.ts
- input data for ValidatorTimelock had empty name causing the explorer to not be able to decode input, now input data is decoded
- fixes https://github.com/matter-labs/block-explorer/issues/490

fix: decode gateway transaction data

---

packages/app/src/composables/useContext.ts

Fix the app to correctly select a network when the previously selected one has been removed or renamed.
If a network in the config is removed or renamed and this network was previously selected by the user, it breaks the network selection, making it impossible to change the network. This scenario should be handled the same way as if no network had been selected.

fix: app network selection

---

packages/api/src/batch/batch.dto.ts
packages/api/src/batch/batch.entity.ts
packages/api/src/batch/batchDetails.dto.ts
packages/api/src/batch/batchDetails.entity.ts
packages/api/test/batch.e2e-spec.ts
packages/app/src/components/batches/Table.vue
packages/app/src/components/transactions/Table.vue
packages/app/src/composables/common/Api.d.ts
packages/app/src/configs/dev.config.json
packages/app/src/configs/staging.config.json
packages/app/tests/e2e/features/artifacts/artifactsSet1.feature
packages/app/tests/e2e/features/redirection/redirectionSet3.feature

Currently, the settlement layer icon for batches and transactions is determined solely based on the `commitChainId` field. As a result, an incorrect settlement layer icon may be shown if the commit, prove and execute transactions are processed by different chains. For example:
https://explorer.zksync.io/batch/501263, where the commit and execute transactions are processed by Ethereum and ZKsync GW, respectively.
To fix this:
1. The API has been updated to return `proveChainId` and `executeChainId` for batch list items.
2. When displaying the settlement layer icon, the appropriate chain ID is used, not just `commitChainId`.
After the fix:
To show a proper settlement layer icon.

fix: settlement layer icon when txs are processed by different layers

---

packages/app/src/configs/staging.config.json

Fix explorer staging config.
The default network (sepolia testnet) should go first, otherwise networks switcher is unable to select the proper network.

fix: explorer staging config

---

packages/api/src/address/address.controller.spec.ts
packages/api/src/address/address.controller.ts

This PR disables access for contract information in Prividium when the user is not the owner.
Closes https://github.com/matter-labs/zksync-prividium/issues/170
Users should not be able to access the contract’s deployed bytecode or its creation transaction.

fix: disable access for contract information when user is not the owner
